apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-python-app1
  template:
    metadata:
      labels:
        app: my-python-app1
    spec:
      containers:
      - name: my-python-app1
        image: abinayapalraj12/python-app:latest
        ports:
        - containerPort: 5000
